version: '3'
services:
  DB:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5433
    volumes:
      - ./db/data:/var/lib/postgresql/data